### ISSUE TITLE
Pkg.build fails on win32 on julia 0.6 final

### ISSUE THREAD

**Issue by davidanthoff** [JuliaDatabases/SQLite.jl#128] opened 2017-06-07 16:12 UTC
The error log is here:
https://ci.appveyor.com/project/davidanthoff/query-jl/build/1.0.223/job/drhdkyrbnvtdh2se

**Comment by davidanthoff** [comment] 2017-06-11 05:10
@quinnj Any hunch what this might be? I'm seeing this in all my CI tests now in all packages that depend on SQLite.jl...

**Comment by davidanthoff** [comment] 2017-06-20 00:04
@quinnj I still see this problem on julia 0.6 final.

**Comment by davidanthoff** [comment] 2017-07-07 11:17
Bump, any plans to fix this in the near future?

**Comment by quinnj** [comment] 2017-07-07 12:46
PRs are welcome!

**Comment by nalimilan** [comment] 2017-07-07 12:46
This failure is weird. [The RPM](https://build.opensuse.org/package/live_build_log/windows:mingw:win32/mingw32-sqlite/openSUSE_Leap_42.2/x86_64) provides `libsqlite3-0.dll`, which is among the aliases. And there would be no reason for it to be present on 64-bit but not on 32-bit. So I guess that means the library fails to load, maybe because it wasn't compiled correctly... Could be worth running `BinDeps.debug("SQLite")` (e.g. via a test PR) to get more details.

**Comment by davidanthoff** [comment] 2017-07-07 16:17
I'm mainly looking for feedback whether someone is planning to fix this or not. I don't have the time to look into this myself. If this will stay broken for a while I might just disable the corresponding unit tests in all the packages that depend on this for now. That wouldn't be a big problem at all, but if someone was planning to fix this soon I might just wait instead.

**Comment by quinnj** [comment] 2017-07-07 16:21
I'm personally tied up in other things at the moment and 32-bit windows support doesn't seem the highest priority to me; I'll take a look in the next few weeks, but disabling might be best for now.

**Comment by nalimilan** [comment] 2017-07-09 14:14
I can reproduce the failure locally on a 64-bit Windows VM with a 32-bit Julia. The library is correctly installed, but it cannot be loaded:
```
julia> Base.Libdl.dlopen("C:\\Users\\milan\\.julia\\v0.6\\WinRPM\\deps\\usr\\i686-w64-mingw32\\sys-root\\mingw\\bin\\libsqlite3-0")
ERROR: could not load library "C:\Users\milan\.julia\v0.6\WinRPM\deps\usr\i686-w64-mingw32\sys-root\mingw\bin\libsqlite3-0"
�
Stacktrace:
 [1] dlopen at .\libdl.jl:97 (repeats 2 times)
```

Note the weird character, which is not printed e.g. if the path points to a nonexistent file. This seems to indicate a bug in `jl_dlerror`, which is supposed to print the error from `GetLastError`. This should probably be fixed in Julia. I've been able to access the error code with this:
```julia
julia> function f()
           ccall(:LoadLibraryExA, Ptr{Void}, (Ptr{UInt8}, Ptr{Void}, UInt),
                 "C:\\Users\\milan\\.julia\\v0.6\\WinRPM\\deps\\usr\\i686-w64-mingw32\\sys-root\\mingw\\bin\\libsqlite3-0",
                 C_NULL, 0x00000008)
           ccall(:GetLastError, Int, ())
       end
f (generic function with 1 method)

julia> f()
127
```

Error 127 is apparently "The specified procedure could not be found. ", and can happen in particular when loading a dependency of the DLL fails. As some posts advised, I've used the Dependency Walker tool to check that all of the DLL's dependency are present, and indeed it appears it needs 64-bit Windows DLLs, which of course are not loadable since it is 32-bit. These are:
```
API-MS-WIN-CORE-CONSOLE-L1-1-0.DLL
API-MS-WIN-CORE-HANDLE-L1-1-0.DLL
API-MS-WIN-CORE-PROFILE-L1-1-0.DLL
API-MS-WIN-CORE-STRING-L1-1-0.DLL
API-MS-WIN-CORE-SYNCH-L1-1-0.DLL
API-MS-WIN-CORE-SYNCH-L1-2-0.DLL
API-MS-WIN-CORE-TIMEZONE-L1-1-0.DLL
API-MS-WIN-CORE-UTIL-L1-1-0.DLL
```

What's funny is that the 64-bit DLL also links to 32-bit ones, but they are different, so that can explain why it works contrary to the 32-bit version:
```
KERNEL32.DLL
KERNELBASE.DLL
MSVCRT.DLL
NTDLL.DLL
```

@tkelman @staticfloat Has it happened before that 32-bit WinRPM libraries where incorrectly linked?

**Comment by tkelman** [comment] 2017-07-09 14:17
it's not the system dlls, it's a difference in libgcc between the winrpm version (gcc 7) and what julia is built with (gcc 5)

**Comment by quinnj** [comment] 2017-09-15 04:15
@nalimilan, @tkelman, any ideas on what can be done here then? I can dust off an old windows box to play around w/ this, but just wanted to check if any of you had any ideas on what to look at/try first.

**Comment by nalimilan** [comment] 2017-09-15 07:57
@tkelman knows better if there's a solution. If not, SQLite might be a good candidate to test the new BinaryProvider.jl system (once it stabilizes a bit).

**Comment by quinnj** [comment] 2018-10-10 02:43
Closing this since we switched to BinaryBuilder

**Closed by quinnj** 2018-10-10 02:43 UTC
