### ISSUE TITLE
SQLite master segfaults on Julia 0.6 rc2 Linux

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaDatabases/SQLite.jl#125] opened 2017-05-24 18:09 UTC
Hey there! I'm getting `Segmentation faults` on the latest version of SQLite with Julia v0.6 rc2 and later (also tested on Julia 0.7 master) running on Linux x64. This happens anytime I run `SQLite.query()` or `Pkg.test("SQLite")`. This happens on multiple systems, so it's not isolated to just a single install. The message displayed often changes based on which method caused the segfault, and is usually quite long (at least 2 pages in length) Here's a snippet of an error:
```
julia> Pkg.test("SQLite")
INFO: Computing test dependencies for SQLite...
INFO: Cloning cache of DataStreamsIntegrationTests from https://github.com/JuliaData/DataStreamsIntegrationTests.jl.git
INFO: Installing DataStreamsIntegrationTests v0.0.2
INFO: Testing SQLite
WARNING: StatsBase.WeightVec is deprecated, use StatsBase.Weights{#7#S, #8#T, #9#V} where #9#V<:AbstractArray{#8#T, 1} where #8#T<:Real where #7#S<:Real instead.
  likely near /home/jpsamaroo/.julia/v0.6/DataArrays/src/reduce.jl:178
WARNING: StatsBase.WeightVec is deprecated, use StatsBase.Weights{#7#S, #8#T, #9#V} where #9#V<:AbstractArray{#8#T, 1} where #8#T<:Real where #7#S<:Real instead.
  likely near /home/jpsamaroo/.julia/v0.6/DataArrays/src/reduce.jl:178
WARNING: StatsBase.WeightVec is deprecated, use StatsBase.Weights{#7#S, #8#T, #9#V} where #9#V<:AbstractArray{#8#T, 1} where #8#T<:Real where #7#S<:Real instead.
  likely near /home/jpsamaroo/.julia/v0.6/DataArrays/src/reduce.jl:178
WARNING: StatsBase.WeightVec is deprecated, use StatsBase.Weights{#7#S, #8#T, #9#V} where #9#V<:AbstractArray{#8#T, 1} where #8#T<:Real where #7#S<:Real instead.
  likely near /home/jpsamaroo/.julia/v0.6/DataArrays/src/reduce.jl:187
WARNING: StatsBase.WeightVec is deprecated, use StatsBase.Weights{#7#S, #8#T, #9#V} where #9#V<:AbstractArray{#8#T, 1} where #8#T<:Real where #7#S<:Real instead.
  likely near /home/jpsamaroo/.julia/v0.6/DataArrays/src/reduce.jl:187
WARNING: StatsBase.WeightVec is deprecated, use StatsBase.Weights{#7#S, #8#T, #9#V} where #9#V<:AbstractArray{#8#T, 1} where #8#T<:Real where #7#S<:Real instead.
  likely near /home/jpsamaroo/.julia/v0.6/DataArrays/src/reduce.jl:187
WARNING: StatsBase.WeightVec is deprecated, use StatsBase.Weights{#7#S, #8#T, #9#V} where #9#V<:AbstractArray{#8#T, 1} where #8#T<:Real where #7#S<:Real instead.
  likely near /home/jpsamaroo/.julia/v0.6/DataArrays/src/extras.jl:8
WARNING: StatsBase.WeightVec is deprecated, use StatsBase.Weights{#7#S, #8#T, #9#V} where #9#V<:AbstractArray{#8#T, 1} where #8#T<:Real where #7#S<:Real instead.
  likely near /home/jpsamaroo/.julia/v0.6/DataArrays/src/extras.jl:26
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/jpsamaroo/.julia/v0.6/NullableArrays/src/operators.jl:128.
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/jpsamaroo/.julia/v0.6/NullableArrays/src/operators.jl:128.
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/jpsamaroo/.julia/v0.6/NullableArrays/src/operators.jl:128.
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/jpsamaroo/.julia/v0.6/NullableArrays/src/operators.jl:128.
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/jpsamaroo/.julia/v0.6/NullableArrays/src/operators.jl:128.

signal (11): Segmentation fault
while loading /home/jpsamaroo/.julia/v0.6/SQLite/test/runtests.jl, in expression starting on line 17
jl_gc_pool_alloc at /opt/julia-0.6/src/gc.c:927
abstract_call_gf_by_type at ./inference.jl:1260
unknown function (ip: 0x7fb19ea64cf6)
jl_call_fptr_internal at /opt/julia-0.6/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /opt/julia-0.6/src/julia_internal.h:356 [inlined]
jl_apply_generic at /opt/julia-0.6/src/gf.c:1930
abstract_call at ./inference.jl:1879
unknown function (ip: 0x7fb19ea609de)
jl_call_fptr_internal at /opt/julia-0.6/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /opt/julia-0.6/src/julia_internal.h:356 [inlined]
jl_apply_generic at /opt/julia-0.6/src/gf.c:1930
abstract_eval_call at ./inference.jl:1909
abstract_eval at ./inference.jl:1932
unknown function (ip: 0x7fb19ea5b966)
jl_call_fptr_internal at /opt/julia-0.6/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /opt/julia-0.6/src/julia_internal.h:356 [inlined]
jl_apply_generic at /opt/julia-0.6/src/gf.c:1930
typeinf_frame at ./inference.jl:2746
typeinf_loop at ./inference.jl:2621
typeinf_frame at ./inference.jl:2491
```

And here's the `versioninfo()` of one of the machines that it's failing on:
```
julia> versioninfo()
Julia Version 0.6.0-rc2.0
Commit 68e911be53 (2017-05-18 02:31 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, westmere)
```

Please let me know if you need anymore information for this one. I might revert to Julia v0.6 rc1 and see if that gets rid of this issue (since this only cropped up last night for me); I'll add an update to this issue if anything changes.

**Comment by quinnj** [comment] 2017-05-24 19:22
Thanks for the detailed report; I'm actually in the middle of a bit of an overhaul of the DataStreams framework, which will change/effect SQLite. I'm hoping to have SQLite 0.6-ready in the next week or two.

**Comment by drhsqlite** [comment] 2017-05-25 00:26
One of the optimizations added to SQLite 3.19.0 was an attempt to "flatten" subqueries or views on the right-hand side of a LEFT JOIN into the main query.  I apparently did not test that new optimization nearly well enough, because it is giving us fits.  See https://www.sqlite.org/src/info/cad1ab4cb7b0fc34 and https://www.sqlite.org/src/info/7fde638e94287d2c for crash bugs caused directly by this new optimization.  We've already done one patch release (3.19.1) and another is forth coming.

If you can send your database schema and the query that is crashing to me via private email (drh at sqlite.org), that will be immensely helpful in fixing up the new optimization so that it is serviceable.

**Comment by jpsamaroo** [comment] 2017-05-25 22:02
@quinnj great to hear, looking forward to testing that out :smile:
@drhsqlite my schema is actually just a simple `(name text, path text)`, and I'm just doing a `select * from table` and parsing the results in Julia. So it probably isn't directly related to the new SQLite optimizations. I'm also running SQLite 3.17.0, so it's even more likely to not be related :smile:

Note that the query does not always fail; it seems to work when done from the REPL. Also, I don't get any segfaults on Julia v0.6 RC1, so it seems like it's mostly isolated to the RC2 changes.

**Comment by quinnj** [comment] 2017-09-15 04:03
@jpsamaroo, is there any way you can share a sample dataset/schema that I could load into a SQLite database to be able to reproduce this issue? I just merged in a bunch of updates for 0.6/0.7, so if we're lucky, it isn't an issue any more. If you'd like to `Pkg.checkout("SQLite"); Pkg.checkout("DataFrames"); Pkg.update()`, you should be able to get the latest code here and you could try reproducing as well.

**Comment by jpsamaroo** [comment] 2017-10-08 19:00
@quinnj I'm so sorry I haven't responded here, I've been super busy between work and getting my own package off the ground. The schema that I initially used has disappeared into the abyss of my filesystem, but I can attest to the fact that it was *exceedingly* simple. Something like 2-3 text columns in a table. It also typically only segfaulted outside of the REPL, when not running within a function.
Something like:
```
using SQLite
db = SQLite.DB("test.sqlite")
SQLite.query(db, "select * from testtable")
```

Anyway, I just ran a `Pkg.test("SQLite")` on Julia 0.6.1-pre.0 after checking out SQLite and DataFrames masters, and all tests passed.

**Comment by quinnj** [comment] 2018-10-10 02:44
Going to close this for now since we haven't had any further reports of similar issues; please re-open if anyone can reproduce.

**Closed by quinnj** 2018-10-10 02:44 UTC
